/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevenueIndexRouteImport } from './routes/revenue/index'
import { Route as RevenueStatementsRouteImport } from './routes/revenue/statements'
import { Route as RevenueImportsRouteImport } from './routes/revenue/imports'
import { Route as RevenueCommissionsRouteImport } from './routes/revenue/commissions'

const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueIndexRoute = RevenueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RevenueRoute,
} as any)
const RevenueStatementsRoute = RevenueStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => RevenueRoute,
} as any)
const RevenueImportsRoute = RevenueImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => RevenueRoute,
} as any)
const RevenueCommissionsRoute = RevenueCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => RevenueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/revenue': typeof RevenueRouteWithChildren
  '/revenue/commissions': typeof RevenueCommissionsRoute
  '/revenue/imports': typeof RevenueImportsRoute
  '/revenue/statements': typeof RevenueStatementsRoute
  '/revenue/': typeof RevenueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/revenue/commissions': typeof RevenueCommissionsRoute
  '/revenue/imports': typeof RevenueImportsRoute
  '/revenue/statements': typeof RevenueStatementsRoute
  '/revenue': typeof RevenueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/revenue': typeof RevenueRouteWithChildren
  '/revenue/commissions': typeof RevenueCommissionsRoute
  '/revenue/imports': typeof RevenueImportsRoute
  '/revenue/statements': typeof RevenueStatementsRoute
  '/revenue/': typeof RevenueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/revenue'
    | '/revenue/commissions'
    | '/revenue/imports'
    | '/revenue/statements'
    | '/revenue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/revenue/commissions'
    | '/revenue/imports'
    | '/revenue/statements'
    | '/revenue'
  id:
    | '__root__'
    | '/'
    | '/revenue'
    | '/revenue/commissions'
    | '/revenue/imports'
    | '/revenue/statements'
    | '/revenue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RevenueRoute: typeof RevenueRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue/': {
      id: '/revenue/'
      path: '/'
      fullPath: '/revenue/'
      preLoaderRoute: typeof RevenueIndexRouteImport
      parentRoute: typeof RevenueRoute
    }
    '/revenue/statements': {
      id: '/revenue/statements'
      path: '/statements'
      fullPath: '/revenue/statements'
      preLoaderRoute: typeof RevenueStatementsRouteImport
      parentRoute: typeof RevenueRoute
    }
    '/revenue/imports': {
      id: '/revenue/imports'
      path: '/imports'
      fullPath: '/revenue/imports'
      preLoaderRoute: typeof RevenueImportsRouteImport
      parentRoute: typeof RevenueRoute
    }
    '/revenue/commissions': {
      id: '/revenue/commissions'
      path: '/commissions'
      fullPath: '/revenue/commissions'
      preLoaderRoute: typeof RevenueCommissionsRouteImport
      parentRoute: typeof RevenueRoute
    }
  }
}

interface RevenueRouteChildren {
  RevenueCommissionsRoute: typeof RevenueCommissionsRoute
  RevenueImportsRoute: typeof RevenueImportsRoute
  RevenueStatementsRoute: typeof RevenueStatementsRoute
  RevenueIndexRoute: typeof RevenueIndexRoute
}

const RevenueRouteChildren: RevenueRouteChildren = {
  RevenueCommissionsRoute: RevenueCommissionsRoute,
  RevenueImportsRoute: RevenueImportsRoute,
  RevenueStatementsRoute: RevenueStatementsRoute,
  RevenueIndexRoute: RevenueIndexRoute,
}

const RevenueRouteWithChildren = RevenueRoute._addFileChildren(RevenueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RevenueRoute: RevenueRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
