/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevenueIndexRouteImport } from './routes/revenue/index'
import { Route as RevenueStatementsRouteImport } from './routes/revenue/statements'
import { Route as RevenueImportsRouteImport } from './routes/revenue/imports'
import { Route as RevenueCommissionsRouteImport } from './routes/revenue/commissions'
import { Route as RevenueStatementsIndexRouteImport } from './routes/revenue/statements/index'
import { Route as RevenueStatementsBrandCodeRouteImport } from './routes/revenue/statements/$brandCode'
import { Route as RevenueStatementsManualEntryRouteImport } from './routes/revenue/statements/manual-entry'
import { Route as RevenueStatementsGapsRouteImport } from './routes/revenue/statements/gaps'
import { Route as RevenueCommissionsIndexRouteImport } from './routes/revenue/commissions/index'
import { Route as RevenueCommissionsResultsRouteImport } from './routes/revenue/commissions/results'
import { Route as RevenueCommissionsSummaryRouteImport } from './routes/revenue/commissions/summary'
import { Route as RevenueCommissionsValidationRouteImport } from './routes/revenue/commissions/validation'
import { Route as RevenueCommissionsValidationBatchIdRouteImport } from './routes/revenue/commissions/validation_.$batchId'

const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueIndexRoute = RevenueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RevenueRoute,
} as any)
const RevenueStatementsRoute = RevenueStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => RevenueRoute,
} as any)
const RevenueImportsRoute = RevenueImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => RevenueRoute,
} as any)
const RevenueCommissionsRoute = RevenueCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => RevenueRoute,
} as any)
const RevenueStatementsIndexRoute = RevenueStatementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RevenueStatementsRoute,
} as any)
const RevenueStatementsBrandCodeRoute = RevenueStatementsBrandCodeRouteImport.update({
  id: '/$brandCode',
  path: '/$brandCode',
  getParentRoute: () => RevenueStatementsRoute,
} as any)
const RevenueStatementsManualEntryRoute = RevenueStatementsManualEntryRouteImport.update({
  id: '/manual-entry',
  path: '/manual-entry',
  getParentRoute: () => RevenueStatementsRoute,
} as any)
const RevenueStatementsGapsRoute = RevenueStatementsGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => RevenueStatementsRoute,
} as any)
const RevenueCommissionsIndexRoute = RevenueCommissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RevenueCommissionsRoute,
} as any)
const RevenueCommissionsResultsRoute = RevenueCommissionsResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => RevenueCommissionsRoute,
} as any)
const RevenueCommissionsSummaryRoute = RevenueCommissionsSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => RevenueCommissionsRoute,
} as any)
const RevenueCommissionsValidationRoute = RevenueCommissionsValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => RevenueCommissionsRoute,
} as any)
const RevenueCommissionsValidationBatchIdRoute = RevenueCommissionsValidationBatchIdRouteImport.update({
  id: '/validation/$batchId',
  path: '/validation/$batchId',
  getParentRoute: () => RevenueCommissionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/revenue': typeof RevenueRouteWithChildren
  '/revenue/commissions': typeof RevenueCommissionsRouteWithChildren
  '/revenue/imports': typeof RevenueImportsRoute
  '/revenue/statements': typeof RevenueStatementsRouteWithChildren
  '/revenue/': typeof RevenueIndexRoute
  '/revenue/commissions/': typeof RevenueCommissionsIndexRoute
  '/revenue/commissions/results': typeof RevenueCommissionsResultsRoute
  '/revenue/commissions/summary': typeof RevenueCommissionsSummaryRoute
  '/revenue/commissions/validation': typeof RevenueCommissionsValidationRoute
  '/revenue/commissions/validation/$batchId': typeof RevenueCommissionsValidationBatchIdRoute
  '/revenue/statements/': typeof RevenueStatementsIndexRoute
  '/revenue/statements/$brandCode': typeof RevenueStatementsBrandCodeRoute
  '/revenue/statements/manual-entry': typeof RevenueStatementsManualEntryRoute
  '/revenue/statements/gaps': typeof RevenueStatementsGapsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/revenue/imports': typeof RevenueImportsRoute
  '/revenue': typeof RevenueIndexRoute
  '/revenue/commissions': typeof RevenueCommissionsIndexRoute
  '/revenue/commissions/results': typeof RevenueCommissionsResultsRoute
  '/revenue/commissions/summary': typeof RevenueCommissionsSummaryRoute
  '/revenue/commissions/validation': typeof RevenueCommissionsValidationRoute
  '/revenue/commissions/validation/$batchId': typeof RevenueCommissionsValidationBatchIdRoute
  '/revenue/statements': typeof RevenueStatementsIndexRoute
  '/revenue/statements/$brandCode': typeof RevenueStatementsBrandCodeRoute
  '/revenue/statements/manual-entry': typeof RevenueStatementsManualEntryRoute
  '/revenue/statements/gaps': typeof RevenueStatementsGapsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/revenue': typeof RevenueRouteWithChildren
  '/revenue/commissions': typeof RevenueCommissionsRouteWithChildren
  '/revenue/imports': typeof RevenueImportsRoute
  '/revenue/statements': typeof RevenueStatementsRouteWithChildren
  '/revenue/': typeof RevenueIndexRoute
  '/revenue/commissions/': typeof RevenueCommissionsIndexRoute
  '/revenue/commissions/results': typeof RevenueCommissionsResultsRoute
  '/revenue/commissions/summary': typeof RevenueCommissionsSummaryRoute
  '/revenue/commissions/validation': typeof RevenueCommissionsValidationRoute
  '/revenue/commissions/validation/$batchId': typeof RevenueCommissionsValidationBatchIdRoute
  '/revenue/statements/': typeof RevenueStatementsIndexRoute
  '/revenue/statements/$brandCode': typeof RevenueStatementsBrandCodeRoute
  '/revenue/statements/manual-entry': typeof RevenueStatementsManualEntryRoute
  '/revenue/statements/gaps': typeof RevenueStatementsGapsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/revenue'
    | '/revenue/commissions'
    | '/revenue/imports'
    | '/revenue/statements'
    | '/revenue/'
    | '/revenue/commissions/'
    | '/revenue/commissions/results'
    | '/revenue/commissions/summary'
    | '/revenue/commissions/validation'
    | '/revenue/commissions/validation/$batchId'
    | '/revenue/statements/'
    | '/revenue/statements/$brandCode'
    | '/revenue/statements/manual-entry'
    | '/revenue/statements/gaps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/revenue/imports'
    | '/revenue'
    | '/revenue/commissions'
    | '/revenue/commissions/results'
    | '/revenue/commissions/summary'
    | '/revenue/commissions/validation'
    | '/revenue/commissions/validation/$batchId'
    | '/revenue/statements'
    | '/revenue/statements/$brandCode'
    | '/revenue/statements/manual-entry'
    | '/revenue/statements/gaps'
  id:
    | '__root__'
    | '/'
    | '/revenue'
    | '/revenue/commissions'
    | '/revenue/imports'
    | '/revenue/statements'
    | '/revenue/'
    | '/revenue/commissions/'
    | '/revenue/commissions/results'
    | '/revenue/commissions/summary'
    | '/revenue/commissions/validation'
    | '/revenue/commissions/validation/$batchId'
    | '/revenue/statements/'
    | '/revenue/statements/$brandCode'
    | '/revenue/statements/manual-entry'
    | '/revenue/statements/gaps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RevenueRoute: typeof RevenueRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue/': {
      id: '/revenue/'
      path: '/'
      fullPath: '/revenue/'
      preLoaderRoute: typeof RevenueIndexRouteImport
      parentRoute: typeof RevenueRoute
    }
    '/revenue/statements': {
      id: '/revenue/statements'
      path: '/statements'
      fullPath: '/revenue/statements'
      preLoaderRoute: typeof RevenueStatementsRouteImport
      parentRoute: typeof RevenueRoute
    }
    '/revenue/imports': {
      id: '/revenue/imports'
      path: '/imports'
      fullPath: '/revenue/imports'
      preLoaderRoute: typeof RevenueImportsRouteImport
      parentRoute: typeof RevenueRoute
    }
    '/revenue/commissions': {
      id: '/revenue/commissions'
      path: '/commissions'
      fullPath: '/revenue/commissions'
      preLoaderRoute: typeof RevenueCommissionsRouteImport
      parentRoute: typeof RevenueRoute
    }
    '/revenue/commissions/': {
      id: '/revenue/commissions/'
      path: '/'
      fullPath: '/revenue/commissions/'
      preLoaderRoute: typeof RevenueCommissionsIndexRouteImport
      parentRoute: typeof RevenueCommissionsRoute
    }
    '/revenue/commissions/results': {
      id: '/revenue/commissions/results'
      path: '/results'
      fullPath: '/revenue/commissions/results'
      preLoaderRoute: typeof RevenueCommissionsResultsRouteImport
      parentRoute: typeof RevenueCommissionsRoute
    }
    '/revenue/commissions/summary': {
      id: '/revenue/commissions/summary'
      path: '/summary'
      fullPath: '/revenue/commissions/summary'
      preLoaderRoute: typeof RevenueCommissionsSummaryRouteImport
      parentRoute: typeof RevenueCommissionsRoute
    }
    '/revenue/commissions/validation': {
      id: '/revenue/commissions/validation'
      path: '/validation'
      fullPath: '/revenue/commissions/validation'
      preLoaderRoute: typeof RevenueCommissionsValidationRouteImport
      parentRoute: typeof RevenueCommissionsRoute
    }
    '/revenue/commissions/validation/$batchId': {
      id: '/revenue/commissions/validation/$batchId'
      path: '/validation/$batchId'
      fullPath: '/revenue/commissions/validation/$batchId'
      preLoaderRoute: typeof RevenueCommissionsValidationBatchIdRouteImport
      parentRoute: typeof RevenueCommissionsRoute
    }
    '/revenue/statements/': {
      id: '/revenue/statements/'
      path: '/'
      fullPath: '/revenue/statements/'
      preLoaderRoute: typeof RevenueStatementsIndexRouteImport
      parentRoute: typeof RevenueStatementsRoute
    }
    '/revenue/statements/$brandCode': {
      id: '/revenue/statements/$brandCode'
      path: '/$brandCode'
      fullPath: '/revenue/statements/$brandCode'
      preLoaderRoute: typeof RevenueStatementsBrandCodeRouteImport
      parentRoute: typeof RevenueStatementsRoute
    }
    '/revenue/statements/manual-entry': {
      id: '/revenue/statements/manual-entry'
      path: '/manual-entry'
      fullPath: '/revenue/statements/manual-entry'
      preLoaderRoute: typeof RevenueStatementsManualEntryRouteImport
      parentRoute: typeof RevenueStatementsRoute
    }
    '/revenue/statements/gaps': {
      id: '/revenue/statements/gaps'
      path: '/gaps'
      fullPath: '/revenue/statements/gaps'
      preLoaderRoute: typeof RevenueStatementsGapsRouteImport
      parentRoute: typeof RevenueStatementsRoute
    }
  }
}

interface RevenueStatementsRouteChildren {
  RevenueStatementsIndexRoute: typeof RevenueStatementsIndexRoute
  RevenueStatementsBrandCodeRoute: typeof RevenueStatementsBrandCodeRoute
  RevenueStatementsManualEntryRoute: typeof RevenueStatementsManualEntryRoute
  RevenueStatementsGapsRoute: typeof RevenueStatementsGapsRoute
}

const RevenueStatementsRouteChildren: RevenueStatementsRouteChildren = {
  RevenueStatementsIndexRoute: RevenueStatementsIndexRoute,
  RevenueStatementsBrandCodeRoute: RevenueStatementsBrandCodeRoute,
  RevenueStatementsManualEntryRoute: RevenueStatementsManualEntryRoute,
  RevenueStatementsGapsRoute: RevenueStatementsGapsRoute,
}

const RevenueStatementsRouteWithChildren = RevenueStatementsRoute._addFileChildren(RevenueStatementsRouteChildren)

interface RevenueCommissionsRouteChildren {
  RevenueCommissionsIndexRoute: typeof RevenueCommissionsIndexRoute
  RevenueCommissionsResultsRoute: typeof RevenueCommissionsResultsRoute
  RevenueCommissionsSummaryRoute: typeof RevenueCommissionsSummaryRoute
  RevenueCommissionsValidationRoute: typeof RevenueCommissionsValidationRoute
  RevenueCommissionsValidationBatchIdRoute: typeof RevenueCommissionsValidationBatchIdRoute
}

const RevenueCommissionsRouteChildren: RevenueCommissionsRouteChildren = {
  RevenueCommissionsIndexRoute: RevenueCommissionsIndexRoute,
  RevenueCommissionsResultsRoute: RevenueCommissionsResultsRoute,
  RevenueCommissionsSummaryRoute: RevenueCommissionsSummaryRoute,
  RevenueCommissionsValidationRoute: RevenueCommissionsValidationRoute,
  RevenueCommissionsValidationBatchIdRoute: RevenueCommissionsValidationBatchIdRoute,
}

const RevenueCommissionsRouteWithChildren = RevenueCommissionsRoute._addFileChildren(RevenueCommissionsRouteChildren)

interface RevenueRouteChildren {
  RevenueCommissionsRoute: typeof RevenueCommissionsRouteWithChildren
  RevenueImportsRoute: typeof RevenueImportsRoute
  RevenueStatementsRoute: typeof RevenueStatementsRouteWithChildren
  RevenueIndexRoute: typeof RevenueIndexRoute
}

const RevenueRouteChildren: RevenueRouteChildren = {
  RevenueCommissionsRoute: RevenueCommissionsRouteWithChildren,
  RevenueImportsRoute: RevenueImportsRoute,
  RevenueStatementsRoute: RevenueStatementsRouteWithChildren,
  RevenueIndexRoute: RevenueIndexRoute,
}

const RevenueRouteWithChildren = RevenueRoute._addFileChildren(RevenueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RevenueRoute: RevenueRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
