name: Docker Build & Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: hnc-partners/hnc-dev/.github/workflows/mf-docker-build.yml@main
    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
